spring:
  datasource:
    # Используем переменные окружения для указания логинов, паролей и урлов
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    properties:
      hibernate:
        # Выключаем показ sql запросов
        show_sql: false

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  zipkin-endpoint: ${ZIPKIN_URL}